config/routes.rb
Rails.application.routes.draw do

root to: 'home#index'

resources :home
resources :venue
get "/venue/:id/new" => 'venues#new'
get "/venue/:id/update" => 'venues#update'
get "/venue/:id/delete" => 'venues#delete'

resources :blog
get "/blog/:id/new" => 'comments#new'
get "/blog/:id/update" => 'comments#update'
get "/blog/:id/delete" => 'comments#delete'

resources :comments
resources :users
# resources :login

get '/login' => 'login#new'
post '/login' => 'login#create'
delete '/logout' => 'login#delete'

get "/sass.html" => 'home#index'

get "/about" => "about#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  # belongs_to :venue
  belongs_to :venue
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :blog_id
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # belongs_to :blog_id
  has_secure_password
  has_many :comments
  end

app/models/venue.rb
class Venue < ApplicationRecord
  # has_many :venue_id
  # belongs_to :venue

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController


  def index
    @all_blogs = Blog.all
  end

  def show
    # @all_venues = Venue.all
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comment.blog_id = params["id"]
    # irb
  end

  def destroy
    blog = Blog.find_by(id: params["id"])
    blog.destroy
    redirect_to "/blog"
  end
    end
    

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def new
  end

  def show
  end

  def index
  end

  def update
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def home
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :check_if_logged_out, only: [:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update]

  def index
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
  end

  def create
    email = params["email"]
    password = params["password"]

    user = User.find_by(email: email)
    # If the user exists and you provided the right password
    if user.present? && user.authenticate(password)

      session[:user_id] = user.id
      redirect_to "/users"

    else
      flash[:login_error] = "The password or email was incorrect"
      # Show the login form again (potentially with a temporary message)
      render :new # Show the new form
    end
  end

  def edit
  end

  def delete
    session[:user_id] = nil
    redirect_to "/users"
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/users"
  end


  # class SessionController < ApplicationController
  #   def new
  #   end

  #   def destroy
  #     session[:user_id] = nil
  #     redirect_to "/users"
  #   end
  # end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def check_if_logged_out
      if @current_user
        flash[:error] = "You are already logged in"
        redirect_to "/users"
      end
    end

    def check_if_logged_in
      unless @current_user
        flash[:error] = "You need to be logged in for that"
        redirect_to "/login"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_out, only:[:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update, :show]
  # before_action :check_if_same_user, only: [:show, :edit]

    def index
    end

    def show
      @user = User.find_by(id: params["id"])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new( user_params )
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path( @user )
      else
        render :new # Show them the Sign Up form again
      end
    end

    def edit
      @user = User.find_by id: params[ "id"]
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end


    private
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      def check_if_logged_out
        if @current_user
          flash[:error] = "You are already logged in"
          redirect_to "/users"
        end
      end

      def check_if_logged_in
        unless @current_user
          flash[:error] = "You need to be logged in for that"
          redirect_to "/login"
        end
      end
  end


#
#   def index
#     @users = User.all
#   end
#
#   def show
#     @user = User.find_by(id: params["id"])
#   end
#
#   def new
#     @user = User.new
#   end
#
#   def create
#     @user = User.new(user_params())
#     if @user.save
#       session[:user_id] = @user.id
#       redirect_to(root_path())
#     else
#       render :new
#     end
#   end
#
#
#
#
#   def edit
#   end
#
#   def destroy
#   end
#
# private
#   def user_params
#     params.require(:user).permit(:name, :email, :password, :password_confirmation)
#   end
#
#   def check_if_logged_out
#     if @current_user
#       flash[:error] = "You are already logged in"
#       redirect_to "/users"
#     end
#   end
#
#   def check_if_logged_in
#     unless @current_user
#       flash[:error] = "You need to be logged in for that"
#       redirect_to "/login"
#     end
#   end
# end

app/controllers/venue_controller.rb
class VenueController < ApplicationController
  def index
    # Do I need to speak to the database?
    # Do I need to pass any information to the views? (as instance variables)
    @all_venues = Venue.all
    # irb
  end

  def show
    @venue = Venue.find_by(id: params['id'])
    @all_venues = Venues.all
  end

  def destroy
    venue = Venue.find_by(id: params["id"])
    venue.destroy
    redirect_to "/venues"
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/users/_form.html.erb
<% unless @user.errors.full_messages.empty? %>

  <% @user.errors.full_messages.each do |msg| %>
    <p>
      <%= msg %>
    </p>
  <% end %>

<% end %>

<!-- <%= form_for @user do |f| %>

<div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="First Name" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>

        <div class="input-field col s6">
          <input placeholder="Surname" id="last_name" type="text" class="validate">
          <label for="last_name">Surname</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Email" id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Password" id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>

      <%= submit_tag "Submit" %>

    </form>
  </div>

<% end %> -->

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render partial: 'form', user: @user %>

app/views/users/index.html.erb
<%= session["important"] %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if flash[:login_error] %>
  <p>
    <%= flash[:login_error] %>
  </p>
<% end %>

<div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="First Name" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>

        <div class="input-field col s6">
          <input placeholder="Surname" id="last_name" type="text" class="validate">
          <label for="last_name">Surname</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Email" id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Password" id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>

      <%= submit_tag "Sign up" %>

    </form>
  </div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  Password Digest:
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>
|
<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blog_path %>

<div class="controls">
  <%= link_to("Add Comment", "/blog/#{@blog.id}/add") %>
  <%= link_to("Edit Comment", "/blog/#{@blog.id}/edit") %>
  <%= link_to("Delete Comment", "/blog/#{@blog.id}", method: :delete, data: { confirm: "Are you sure?" }) %>
</div>

app/views/venue/index.html.erb
<!-- <h1>Food + Drink</h1>

<div class="row">

<div class="image">

</div>


</div>

  <% @all_venues.each do |venue| %>
  <div><%= venue.venue %></div>
  <%= link_to venue_path(venue) %>
  <hr>
  <% end %>

</div> -->

<h1>Food + Drink<br>
    <small>Find the best places to eat + drink near you</small>
</h1>

<div class="container">
    <div class="row">
      <% @all_venues.each do |venue| %>
        <div class="col-sm-4">
            <div class="col-sm-12 thumbnail text-center img-responsive">
                <%= link_to(image_tag(w.image, style: "width: 300px; height: 200px; margin-bottom: 20px; box-shadow: 5px 5px 10px rgba(0, 0, 0, .3)", class: "img-responsive"), venue_path(w.id) ) %>
                <div class="caption">
                    <h4><strong><%= link_to(w.name, venue_path(w), style: "color: #fff; text-shadow: 5px 5px 5px black;") %></strong></h4>
                </div>
            </div>
        </div>
      <% end %>
    </div>
</div>

app/views/venue/show.html.erb
<!-- <% @all_venues.each do |venue| %> -->
  <h5><%= venue.venue %></h5>
  <h6><%= venue.category %></h3>
  <h6><%= venue.address %></h6>
  <h6><%= venue.suburb %></h6>
  <h6><%= venue.website %></h6>
  <%= link_to"View website" %>
<% end %>

<div class="controls">
  <%= link_to("Add Comment", "/venue/#{@venue.id}/new") %>
  <%= link_to("Edit Comment", "/venue/#{@venue.id}/update") %>
  <%= link_to("Delete Comment", "/venue/#{@venue.id}", method: :delete, data: { confirm: "Are you sure?" }) %>
</div>



<h1><%= @venue.venue %></h1>
<div class="row">
    <div class="col-md-6 thumbnail">

    </div>

  