config/routes.rb
Rails.application.routes.draw do

root to: 'home#index'

resources :home
resources :venue
get "/venue/:id/new" => 'venues#new'
get "/venue/:id/update" => 'venues#update'
get "/venue/:id/delete" => 'venues#delete'

resources :blog
get "/blog/:id/new" => 'comments#new'
get "/blog/:id/update" => 'comments#update'
get "/blog/:id/delete" => 'comments#delete'

resources :comments
resources :users
# resources :login

get '/login' => 'login#new'
post '/login' => 'login#create'
delete '/logout' => 'login#delete'

get "/sass.html" => 'home#index'

get "/about" => "about#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  # belongs_to :venue
  belongs_to :venue
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :blog_id
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # belongs_to :blog_id
  has_secure_password
  has_many :comments
  end

app/models/venue.rb
class Venue < ApplicationRecord
  # has_many :venue_id
  # belongs_to :venue

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController


  def index
    @all_blogs = Blog.all
  end

  def show
    # @all_venues = Venue.all
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comment.blog_id = params["id"]
    # irb
  end

  def destroy
    blog = Blog.find_by(id: params["id"])
    blog.destroy
    redirect_to "/blog"
  end
    end
    

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def new
  end

  def show
  end

  def index
  end

  def update
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    # @comment = Comment.find_by(id: params['id'])
      @comment = Comment.new
  end

  def show
    @comment = Comment.find_by(id: params['id'])
  end

  def index
    @comments = Comment.all
  end

def create
    @comment = Comment.new(comment_params)
    respond_to do |format|

    if @comment.save
      session[:user_id] = @user.id
      redirect_to user_path( @comment )
      redirect_to blog_path( blog )
    else
      format.html { render 'new'} ## Specify the format in which you are rendering "new" page
      format.json { render json: @comment.errors } ## You might want to specify a json format as well
    end

    end
  end
end

  def destroy
    comment = Comment.find_by(id: params["id"])
    comment.destroy
    redirect_to "/blog"
  end


private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id)
    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def home
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :check_if_logged_out, only: [:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update]

  def index
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
  end

  def create
    email = params["email"]
    password = params["password"]

    user = User.find_by(email: email)
    # If the user exists and you provided the right password
    if user.present? && user.authenticate(password)

      session[:user_id] = user.id
      redirect_to "/users"

    else
      flash[:login_error] = "The password or email was incorrect"
      # Show the login form again (potentially with a temporary message)
      render :new # Show the new form
    end
  end

  def edit
  end

  def delete
    session[:user_id] = nil
    redirect_to "/users"
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/users"
  end


  # class SessionController < ApplicationController
  #   def new
  #   end

  #   def destroy
  #     session[:user_id] = nil
  #     redirect_to "/users"
  #   end
  # end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def check_if_logged_out
      if @current_user
        flash[:error] = "You are already logged in"
        redirect_to "/users"
      end
    end

    def check_if_logged_in
      unless @current_user
        flash[:error] = "You need to be logged in for that"
        redirect_to "/login"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_out, only:[:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update, :show]
  # before_action :check_if_same_user, only: [:show, :edit]

    def index
    end

    def show
      @user = User.find_by(id: params["id"])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new( user_params )
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path( @user )
      else
        render :new # Show them the Sign Up form again
      end
    end

    def edit
      @user = User.find_by id: params[ "id"]
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end


    private
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      def check_if_logged_out
        if @current_user
          flash[:error] = "You are already logged in"
          redirect_to "/users"
        end
      end

      def check_if_logged_in
        unless @current_user
          flash[:error] = "You need to be logged in for that"
          redirect_to "/login"
        end
      end
  end


#
#   def index
#     @users = User.all
#   end
#
#   def show
#     @user = User.find_by(id: params["id"])
#   end
#
#   def new
#     @user = User.new
#   end
#
#   def create
#     @user = User.new(user_params())
#     if @user.save
#       session[:user_id] = @user.id
#       redirect_to(root_path())
#     else
#       render :new
#     end
#   end
#
#
#
#
#   def edit
#   end
#
#   def destroy
#   end
#
# private
#   def user_params
#     params.require(:user).permit(:name, :email, :password, :password_confirmation)
#   end
#
#   def check_if_logged_out
#     if @current_user
#       flash[:error] = "You are already logged in"
#       redirect_to "/users"
#     end
#   end
#
#   def check_if_logged_in
#     unless @current_user
#       flash[:error] = "You need to be logged in for that"
#       redirect_to "/login"
#     end
#   end
# end

app/controllers/venue_controller.rb
class VenueController < ApplicationController
  def index
    # Do I need to speak to the database?
    # Do I need to pass any information to the views? (as instance variables)
    @all_venues = Venue.all
    # irb
  end

  def show
    @venue = Venue.find_by(id: params['id'])
    @all_venues = Venues.all
  end

  def destroy
    venue = Venue.find_by(id: params["id"])
    venue.destroy
    redirect_to "/venues"
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/blog/_form.html.erb
<%= form_for @comment do |f| %>
    <p>
    <%= f.label :comment %>
    <%= f.text_field :comment, required: true %>
  </p>
  <%= f.submit %>
<% end %>

app/views/blog/index.html.erb
<h1>Blog</h1>

<div class="container">
  <% @all_blogs.each do |blog| %>

  <div class="section">
    <h4><%= link_to(blog.title, "/blog/#{blog.id}") %></h4>
  </div>

  <div class="divider"></div>

  <% end %>
</div>

app/views/blog/new.html.erb
<h1>Add a Comment</h1>

<%= f.hidden_field :idea_id %>

app/views/blog/show.html.erb
<h1>Blog</h1>

<h4><% @blog.title %></h4>
<h5><%= @blog.tagline %></h5>
<h6> <%= @blog.copy %></h6>

<img src="https://www.broadsheet.com.au/media/cache/94/97/949766164220ab431bc5480e7eb1020c.jpg">

<div class="controls">
  <%= link_to("Add Comment", "/blog/#{@blog.id}/new") %>
  <%= link_to("Edit Comment", "/blog/#{@blog.id}/update") %>
  <%= link_to("Delete Comment", "/blog/#{@blog.id}", method: :delete, data: { confirm: "Are you sure?" }) %>
</div>

<!-- <%= link_to "Visit Website", "/blog/show" %> -->

<% @blog.comments.each do |comment| %>
  <div>
    <strong><%= comment.user.name %></strong>
    <br>
    <p><%= comment.
     %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>

<% if @current_user.present? %>

  <%= form_for @comment do |f| %>
      <p>
        <!-- <%= f.label :input %> -->
        <%= f.hidden_field :blog, :value => params["id"] %>

      <%= f.label :input %>
      <%= f.text_field :input %>
    </p>
    <%= f.submit %>
  <% end %>

<% end %>

app/views/blog/update.html.erb
<h1>Edit Comment</h1>

<%= render( partial: "form" ) %>

app/views/comments/_form.html.erb
<!-- <%= form_for @comment do |f| %>
    <p>
    <%= f.label :input %>
    <%= f.text_field :input %>
  </p>
  <%= f.submit %>
<% end %> -->

<!-- comment has:

id
input => form
name = @current_user.name
blog_id = params["id"]
user_id = @current_user.id -->

<%= form_for @comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :input %>
    <%= f.text_field :input %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit your Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |post| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= comment.author %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h2>Add a comment</h2>

<%= form_for (@comment) do |f| %>

  <p>
    <%= f.label :input %>
    <%= f.text_area :input, required: true %>
  </p>

  <%= f.submit %>
<% end %>

<%= form_for(@comment) do |f| %>

  <div class="field">
    <%= f.text_area :input, placeholder: "Post feedback or contribute content
    to this work!" %>
  </div>
  <%= f.submit "Post", class: "btn btn-small btn-primary" %>
<% end %>

app/views/comments/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

<h1><%= @post.heading %></h1>

<p><%= @post.content %></p>

<%= @post.user.email %>

app/views/comments/update.html.erb
<h1>Comment#update</h1>
<p>Find me in app/views/comment/update.html.erb</p>